### ISSUE TITLE
HUD Main Window won't come up

### ISSUE THREAD

**Issue by liadka** [philroberts/FPDB-for-OSX#64]
Mac OS 10.15.7, using python27.
after I check the 'Start Auto Import' checkbox, the error bellow is printed to the terminal and no window comes up

opening pipe to HUD
Traceback (most recent call last):
  File "/Users/liadka/FPDB-for-OSX-0.41.0-rc8/pyfpdb/HUD_main.pyw", line 65, in <module>
    import OSXTables as Tables
  File "/Users/liadka/FPDB-for-OSX-0.41.0-rc8/pyfpdb/OSXTables.py", line 32, in <module>
    import AppKit # Work around some pyinstaller weirdness.
ImportError: No module named AppKit

**Comment by liadka** [comment]
Issue is resolved.
I had to install two more packages.
py27-pyobjc-cocoa
py27-pyobjc
